// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/proto/naturaldate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NaturalDateClient is the client API for NaturalDate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NaturalDateClient interface {
	Parse(ctx context.Context, in *ParseNaturalDateRequest, opts ...grpc.CallOption) (*ParseNaturalDateResponse, error)
}

type naturalDateClient struct {
	cc grpc.ClientConnInterface
}

func NewNaturalDateClient(cc grpc.ClientConnInterface) NaturalDateClient {
	return &naturalDateClient{cc}
}

func (c *naturalDateClient) Parse(ctx context.Context, in *ParseNaturalDateRequest, opts ...grpc.CallOption) (*ParseNaturalDateResponse, error) {
	out := new(ParseNaturalDateResponse)
	err := c.cc.Invoke(ctx, "/api.NaturalDate/Parse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NaturalDateServer is the server API for NaturalDate service.
// All implementations must embed UnimplementedNaturalDateServer
// for forward compatibility
type NaturalDateServer interface {
	Parse(context.Context, *ParseNaturalDateRequest) (*ParseNaturalDateResponse, error)
	mustEmbedUnimplementedNaturalDateServer()
}

// UnimplementedNaturalDateServer must be embedded to have forward compatible implementations.
type UnimplementedNaturalDateServer struct {
}

func (UnimplementedNaturalDateServer) Parse(context.Context, *ParseNaturalDateRequest) (*ParseNaturalDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedNaturalDateServer) mustEmbedUnimplementedNaturalDateServer() {}

// UnsafeNaturalDateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NaturalDateServer will
// result in compilation errors.
type UnsafeNaturalDateServer interface {
	mustEmbedUnimplementedNaturalDateServer()
}

func RegisterNaturalDateServer(s grpc.ServiceRegistrar, srv NaturalDateServer) {
	s.RegisterService(&NaturalDate_ServiceDesc, srv)
}

func _NaturalDate_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseNaturalDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaturalDateServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.NaturalDate/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaturalDateServer).Parse(ctx, req.(*ParseNaturalDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NaturalDate_ServiceDesc is the grpc.ServiceDesc for NaturalDate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NaturalDate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.NaturalDate",
	HandlerType: (*NaturalDateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _NaturalDate_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/naturaldate.proto",
}
