// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/proto/naturaldate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseNaturalDateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NaturalDate string                 `protobuf:"bytes,1,opt,name=naturalDate,proto3" json:"naturalDate,omitempty"`
	BaseDate    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=baseDate,proto3" json:"baseDate,omitempty"`
}

func (x *ParseNaturalDateRequest) Reset() {
	*x = ParseNaturalDateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_naturaldate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseNaturalDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseNaturalDateRequest) ProtoMessage() {}

func (x *ParseNaturalDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_naturaldate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseNaturalDateRequest.ProtoReflect.Descriptor instead.
func (*ParseNaturalDateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_naturaldate_proto_rawDescGZIP(), []int{0}
}

func (x *ParseNaturalDateRequest) GetNaturalDate() string {
	if x != nil {
		return x.NaturalDate
	}
	return ""
}

func (x *ParseNaturalDateRequest) GetBaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BaseDate
	}
	return nil
}

type ParseNaturalDateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParsedDate *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=parsedDate,proto3" json:"parsedDate,omitempty"`
}

func (x *ParseNaturalDateResponse) Reset() {
	*x = ParseNaturalDateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_naturaldate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseNaturalDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseNaturalDateResponse) ProtoMessage() {}

func (x *ParseNaturalDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_naturaldate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseNaturalDateResponse.ProtoReflect.Descriptor instead.
func (*ParseNaturalDateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_naturaldate_proto_rawDescGZIP(), []int{1}
}

func (x *ParseNaturalDateResponse) GetParsedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ParsedDate
	}
	return nil
}

var File_api_proto_naturaldate_proto protoreflect.FileDescriptor

var file_api_proto_naturaldate_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x61, 0x6c, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x17, 0x50, 0x61, 0x72, 0x73, 0x65, 0x4e, 0x61, 0x74, 0x75,
	0x72, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x36, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65, 0x22, 0x56, 0x0a, 0x18, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x4e, 0x61, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x73, 0x65, 0x64, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x73, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x32, 0x53, 0x0a, 0x0b, 0x4e, 0x61, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x44, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x73, 0x65, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x61, 0x72, 0x73, 0x65, 0x4e, 0x61, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x4e, 0x61, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x41, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6a, 0x61, 0x72, 0x6b, 0x65, 0x2d, 0x78, 0x79, 0x7a, 0x2f, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x2f, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x0b, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x61, 0x6c, 0x64, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_naturaldate_proto_rawDescOnce sync.Once
	file_api_proto_naturaldate_proto_rawDescData = file_api_proto_naturaldate_proto_rawDesc
)

func file_api_proto_naturaldate_proto_rawDescGZIP() []byte {
	file_api_proto_naturaldate_proto_rawDescOnce.Do(func() {
		file_api_proto_naturaldate_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_naturaldate_proto_rawDescData)
	})
	return file_api_proto_naturaldate_proto_rawDescData
}

var file_api_proto_naturaldate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_naturaldate_proto_goTypes = []interface{}{
	(*ParseNaturalDateRequest)(nil),  // 0: api.ParseNaturalDateRequest
	(*ParseNaturalDateResponse)(nil), // 1: api.ParseNaturalDateResponse
	(*timestamppb.Timestamp)(nil),    // 2: google.protobuf.Timestamp
}
var file_api_proto_naturaldate_proto_depIdxs = []int32{
	2, // 0: api.ParseNaturalDateRequest.baseDate:type_name -> google.protobuf.Timestamp
	2, // 1: api.ParseNaturalDateResponse.parsedDate:type_name -> google.protobuf.Timestamp
	0, // 2: api.NaturalDate.Parse:input_type -> api.ParseNaturalDateRequest
	1, // 3: api.NaturalDate.Parse:output_type -> api.ParseNaturalDateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_naturaldate_proto_init() }
func file_api_proto_naturaldate_proto_init() {
	if File_api_proto_naturaldate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_naturaldate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseNaturalDateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_naturaldate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseNaturalDateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_naturaldate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_naturaldate_proto_goTypes,
		DependencyIndexes: file_api_proto_naturaldate_proto_depIdxs,
		MessageInfos:      file_api_proto_naturaldate_proto_msgTypes,
	}.Build()
	File_api_proto_naturaldate_proto = out.File
	file_api_proto_naturaldate_proto_rawDesc = nil
	file_api_proto_naturaldate_proto_goTypes = nil
	file_api_proto_naturaldate_proto_depIdxs = nil
}
